on: [push]
jobs:
  notify:
    runs-on: ubuntu-latest
    container: bonyuta0204/github-remainder
    steps:
      - uses: actions/checkout@v2
      - run: "./github-remainder-exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
